[package]
name = "examples-grpc"
version = "0.12.0-alpha.0"
edition = "2021"
publish = false

[dependencies]
init-tracing-opentelemetry = { path = "../../init-tracing-opentelemetry", features = [
  "otlp",
  "tracing_subscriber_ext",
] }
prost = "0.11.2"
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.9", features = [
  "transport",
  "channel",
  "codegen",
], default-features = false }
tonic-health = "0.9"
tonic-reflection = "0.9"
tonic-tracing-opentelemetry = { path = "../../tonic-tracing-opentelemetry" }

[build-dependencies]
tonic-build = { version = "0.9", default-features = false, features = [
  "transport",
  "prost",
] }


[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
