[package]
name = "examples-grpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum-tracing-opentelemetry = { path = "../../axum-tracing-opentelemetry", features = [
  "otlp",
  "tracing_subscriber_ext",
] }
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.8.2", features = [
  "transport",
  "channel",
  "codegen",
], default-features = false }

[build-dependencies]
tonic-build = { version = "0.8.2", default-features = false, features = [
  "transport",
  "prost",
] }
prost = "0.11.2"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
