[workspace]

members = ["init-tracing-opentelemetry", "axum-tracing-opentelemetry"]

[workspace.metadata.release]
pre-release-commit-message = ":rocket: (cargo-release) version {{version}}"
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"
tag-message = ":bookmark: {{version}}"
