[package]
name = "tracing-opentelemetry-instrumentation-sdk"
description = "A set of helpers to build OpenTelemetry instrumentation based on `tracing` crate."
version = "0.12.0-alpha.2"
edition = "2021"
readme = "README.md"
license = "CC0-1.0"
keywords = ["tracing", "opentelemetry"]
categories = [
  "development-tools::debugging",
  "development-tools::profiling",
  "web-programming",
]
repository = "https://github.com/davidB/toolkit-tracing-opentelemetry"
homepage = "https://github.com/davidB/toolkit-tracing-opentelemetry/tracing-opentelemetry-instrumentation-sdk"

[dependencies]
http = { version = "^0.2", optional = true }
opentelemetry_api = { version = "0.19", features = [
  "trace",
], default-features = false }
# opentelemetry-semantic-conventions = { version = "0.11" }
opentelemetry-http = "0.8"
tracing = "0.1"
tracing-opentelemetry = "0.19"

[dev-dependencies]
assert2 = "0.3"
rstest = "0.17"

[features]

default = []
http = ["dep:http"]
