[package]
name = "fake-opentelemetry-collector"
description = "A Fake (basic) opentelemetry collector, useful to test what is collected opentelemetry"
version = "0.11.0"
edition = "2021"
readme = "README.md"
license = "CC0-1.0"
keywords = ["tracing", "opentelemetry", "faker", "mock"]
categories = ["development-tools::testing"]
repository = "https://github.com/davidB/toolkit-tracing-opentelemetry"
homepage = "https://github.com/davidB/toolkit-tracing-opentelemetry/fake-opentelemetry-collector"

[dependencies]
opentelemetry_api = "0.19"
opentelemetry-proto = { version = "0.2", features = ["gen-tonic", "traces"] }
rstest = "0.17"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
time = { version = "0.3", features = ["macros"] }
hex = "0.4"
tokio-stream = { version = "0.1", features = ["net"] }
# need tokio runtime to run smoke tests.
opentelemetry_sdk = { features = [
  "trace",
  "rt-tokio",
  "testing",
], version = "0.19" }
tracing = "0.1"
futures = "0.3"
tonic = "0.8"
tokio = { version = "1.27", features = ["full"] }
opentelemetry-otlp = { version = "0.12" }
opentelemetry = { version = "0.19", features = [
  "rt-tokio",
  "trace",
], default-features = false }

[dev-dependencies]
assert2 = "0.3"
hyper = "0.14"
insta = { version = "1.29.0", features = ["yaml", "redactions"] }
rstest = "0.17"
