[package]
name = "fake-opentelemetry-collector"
description = "A Fake (basic) opentelemetry collector, useful to test what is collected opentelemetry"
version = "0.12.0-alpha.0"
edition = "2021"
readme = "README.md"
license = "CC0-1.0"
keywords = ["tracing", "opentelemetry", "faker", "mock"]
categories = ["development-tools::testing"]
repository = "https://github.com/davidB/toolkit-tracing-opentelemetry"
homepage = "https://github.com/davidB/toolkit-tracing-opentelemetry/fake-opentelemetry-collector"

[dependencies]
futures = "0.3"
hex = "0.4"
opentelemetry = { version = "0.19", features = [
  "rt-tokio",
  "trace",
], default-features = false }
opentelemetry-otlp = { version = "0.12" }
opentelemetry-proto = { version = "0.2", features = ["gen-tonic", "traces"] }
opentelemetry_api = "0.19"
# need tokio runtime to run smoke tests.
opentelemetry_sdk = { features = [
  "trace",
  "rt-tokio",
  "testing",
], version = "0.19" }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.27", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.8" #should be sync with opentelemetry-proto
tracing = "0.1"

[dev-dependencies]
assert2 = "0.3"
hyper = "0.14"
insta = { version = "1.29.0", features = ["yaml", "redactions"] }
