[package]
name = "testing-tracing-opentelemetry"
description = "helpers to help testing app + tracing + opentelemetry."
readme = "README.md"
keywords = ["tracing", "opentelemetry"]
categories = ["development-tools::testing"]
homepage = "https://github.com/davidB/toolkit-tracing-opentelemetry/testing-tracing-opentelemetry"
publish = false
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
assert2 = "0.3"
fake-opentelemetry-collector = { path = "../fake-opentelemetry-collector", version = "0.12.0-alpha.6" }
insta = { version = "1.29.0", features = ["yaml", "redactions"] }
opentelemetry = "0.19"
opentelemetry_api = "0.19"
serde_json = "1.0.79"
tracing = "0.1"
tracing-opentelemetry = "0.19"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
  "json",
] }
